### ISSUE TITLE
New release of ghc-events

### ISSUE THREAD

**Issue by mpickering** [haskell/ghc-events#110]
Is it possible to make a new release of ghc-events?

The latest version on hackage doesn't support eras profiling (2023-04, 18 months ago).

**Comment by Mikolaj** [comment]
@teofilC has kindly offered to maintain ghc-events and ThreadScope at https://github.com/haskell/ThreadScope/pull/130#issuecomment-2452141889 and I think we should take the offer. Any objections? @simonmar, @maoe?

**Comment by maoe** [comment]
No objection from me.

**Comment by Mikolaj** [comment]
OK, great, I hear no objections, so let's welcome @TeofilC and let's give him all the needed permissions.

@TeofilC: I've given you write permissions to the ghc-events and ThreadScope repos. Let me know if you need anything more there. What's your handle on Hackage?

**Comment by Mikolaj** [comment]
> Thanks @Mikolaj ! I'm happy to help. I should have a release of ghc-events out today or tomorrow.

\o/

> My handle on Hackage is [teo](https://hackage.haskell.org/user/teo)

Thank you. I've added you on Hackage for both packages.

**Comment by Mikolaj** [comment]
Well done!
