### ISSUE TITLE
Update the maintainer field

### ISSUE THREAD

**Issue by maoe** [haskell/ghc-events#17]
The maintainer field in the cabal file says this library is maintained by @simonmar but it seems to me that it's currently maintained by @Mikolaj and probably @kvelicka. Should we update the cabal file?

**Comment by Mikolaj** [comment]
I'm quite sure Simon is still the maintainer. I'm just a humble contributor; initially as an employee of Well-Typed, now in my free time, as a ghc-events/ThreadScope/Haskell user.

**Comment by maoe** [comment]
I see. Thanks for the quick response. I'll just close this now.

**Comment by simonmar** [comment]
I'm not a very active maintainer, I'd be happy to hand official maintainership over to someone who had more time to devote. I'll probably keep an eye things, but that's all.

**Comment by maoe** [comment]
Thanks for the clarification. I'm happy to take over the maitainership but I'd like to contribute some code before doing that. I have a few open PRs and plan to do a few more.

**Comment by kvelicka** [comment]
I was interested in maintaining ghc-events too but evidently you've been devoting more time/effort to the project lately, so I'm happy for you to take over the reins once you're comfortable.

**Comment by maoe** [comment]
I'd like to bring this up again.

@simonmar I'm happy to be a co-maintainer.

I'm planning to try a few things:
* add support for the heap profiling events: #29
    * I'm also thinking to extend the heap profiling support in the eventlog framework further: https://github.com/ghc/ghc/pull/32#issuecomment-296340706
* speed up the decoder
* add some indexing support for huge eventlog files
    * I'm not sure if this ends up in threadscope or in this library though

Anyway, I'd like to speed up the development and release of this library.

**Comment by simonmar** [comment]
@maoe Thanks for the offer! It looks like you already have write access to the repo, so you're good to go.

**Comment by maoe** [comment]
@simonmar Sorry I wasn't clear enough.

Yes I have write access but I don't have permissions to release a new version to Hackage. Are you fine to add me to the maintainers group?
