### ISSUE TITLE
v0.5 Hackage release?

### ISSUE THREAD

**Issue by mboes** [haskell/ghc-events#26]
I notice that the README speaks of a 0.5 release, but on Hackage the latest release currently is 0.4.4.0. Any plans to upload v0.5 to Hackage?

**Comment by maoe** [comment]
+1 to releasing 0.5 (or 0.6 because we've changed the API since we bumped the version to 0.5 on master).

I'm happy to do it if the current maintainers are happy to add me to the maintainers group. I already have the commit bit for this repo.

**Comment by kvelicka** [comment]
I'm happy with your changes (i.e. 0.6) but I don't have the permissions to add you to the maintainers list I'm afraid.

**Comment by simonmar** [comment]
@maoe what's your Hackage username?

**Comment by maoe** [comment]
@simonmar I'm MitsutoshiAoe

**Comment by simonmar** [comment]
Done!

**Comment by maoe** [comment]
Released v0.6.0 on Hackage: https://hackage.haskell.org/package/ghc-events-0.6.0
