### ISSUE TITLE
Support new field 'par_balanced_copied_bytes' of EVENT_GC_STATS_GHC

### ISSUE THREAD

**Issue by duog** [haskell/ghc-events#31]
This field was added in [this commit](https://github.com/ghc/ghc/commit/7c9e356de1114ab3e31f2d6d03e83672076dd533).

I would like to add support for this to ghc-events, if you could provide some guidance on how you would like this done.

The options I see are:
* add a `Maybe Int` to the `GCStatsGC` constructor
* Add a GCStatsGC data type, with two constructors (perhaps GCStatsGC_V1, GCStatsGC_V2?) where the second has an additional field. This is my preference.

I would also like to add a function 
```haskell
--| Computes the cumulative parallel work balance of the argument garbage collections.   
workBalance :: [GCStatsGC] -> Double
```

**Comment by maoe** [comment]
Do you mean `GCStatsGHC` rather than `GCStatsGC`?

As to which option to choose, I guess it's a good idea to try both in the threadscope code base to see which one is better to work with.

**Comment by duog** [comment]
Yes I do mean GCStatsGHC. I'll try both with threadscope as you suggest. It might be a week or two before I get to this.
