### ISSUE TITLE
Can we get a release?

### ISSUE THREAD

**Issue by treeowl** [haskell/ghc-events#34]
The version on Hackage does not yet support heap profiling. It would be nice to get that released, I think.

**Comment by maoe** [comment]
Sure, I can do it.

**Comment by maoe** [comment]
Done https://hackage.haskell.org/package/ghc-events-0.7.0

**Comment by treeowl** [comment]
Thanks!

On Oct 4, 2017 1:12 AM, "Mitsutoshi Aoe" <notifications@github.com> wrote:

Done https://hackage.haskell.org/package/ghc-events-0.7.0

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/haskell/ghc-events/issues/34#issuecomment-334051722>,
or mute the thread
