### ISSUE TITLE
Package bounds need to be restricted for old releases

### ISSUE THREAD

**Issue by vmchale** [haskell/ghc-events#44]
As visible on [hackage](https://matrix.hackage.haskell.org/#/package/ghc-events), some package bounds are not strict enough.

**Comment by Mikolaj** [comment]
You mean, for old releases of GHC? E.g., it should refuse compiling under GHC 7.4.2?

**Comment by maoe** [comment]
I'll tighten the lower bound for base.

**Comment by vmchale** [comment]
Unfortunately, the bounds still need to be restricted on Hackage (otherwise the solver will pick incorrectly) - do you know who has the access to do this?

**Comment by maoe** [comment]
I do and I fixed bounds on Hackage: https://matrix.hackage.haskell.org/#/package/ghc-events

**Comment by vmchale** [comment]
Thanks!
