### ISSUE TITLE
Drop support for GHC < 8

### ISSUE THREAD

**Issue by TeofilC** [haskell/ghc-events#88]
My understanding is that this library has to work around incompatibilities between different encodings used by old versions of GHC.

I feel like dropping support for those old versions would help simplify the library and unblock some of the open issues.

I'm suggesting dropping compatibility with anything before GHC 8.0.1, which was released in May 2016. I think that's quite conservative but would still allow dropping all the special cases to deal with old GHCs afaict.

**Comment by Mikolaj** [comment]
I think that's fair. Over 5 years of compatibility and people with ancient GHCs can use older versions of ghc-events.
